apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
   name: tekton-deploy-role
   namespace: default
rules:
# We may want the pipeline to deploy in the cluster and update pods
- apiGroups: [""]
  resources: ["deployments","pods"]
  verbs: ["get", "create", "update", "patch","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
   name: tekton-role-binding
   namespace: default
roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: Role
   name: tekton-deploy-role
subjects:
- kind: ServiceAccount
  name: tekton-sa
  namespace: default